

# Get the current build date
IF(NOT BUILD_DATE)
  # Get the current build_date
  STRING(TIMESTAMP "BUILD_DATE" "%d-%m-%Y")
ENDIF()

# Include DispUtils for MSG_HDR and MSG_STR macros
INCLUDE(DispUtils)

# Macro to display system info
MACRO(DISP_SYS_INFO)
  MSG_HDR("System Info")
  MSG_STR("CMAKE_VERSION            : ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}")
  MSG_STR("CMAKE_SYSTEM             : ${CMAKE_SYSTEM}")
  MSG_STR("CMAKE_SYSTEM_NAME        : ${CMAKE_SYSTEM_NAME}")
  MSG_STR("CMAKE_SYSTEM_VERSION     : ${CMAKE_SYSTEM_VERSION}")
  MSG_STR("CMAKE_SYSTEM_PROCESSOR   : ${CMAKE_SYSTEM_PROCESSOR}")
  MSG_STR("CMAKE_PREFIX_PATH        : ${CMAKE_PREFIX_PATH}")
  MSG_STR("CMAKE_SOURCE_DIR         : ${CMAKE_SOURCE_DIR}")
  MSG_STR("CMAKE_BINARY_DIR         : ${CMAKE_BINARY_DIR}")
ENDMACRO()

# Macro to display project info
MACRO(DISP_PROJ_INFO)
  MSG_HDR("Project Info")
  MSG_STR("CMAKE_PROJECT_NAME   : ${CMAKE_PROJECT_NAME}")
  MSG_STR("PROJECT_BINARY_DIR   : ${PROJECT_BINARY_DIR}")
  MSG_STR("PROJECT_SOURCE_DIR   : ${PROJECT_SOURCE_DIR}")
  MSG_STR("BUILD_DATE           : ${BUILD_DATE}")
ENDMACRO()


# Macro to display c/c++ compiler info 
MACRO(DISP_CXX_INFO)
  MSG_HDR("Compiler Info")
  MSG_STR("CMAKE_C_COMPILER           : ${CMAKE_C_COMPILER}")
  MSG_STR("CMAKE_C_COMPILER_VERSION   : ${CMAKE_C_COMPILER_VERSION}")
  MSG_STR("CMAKE_CXX_COMPILER         : ${CMAKE_CXX_COMPILER}")
  MSG_STR("CMAKE_CXX_COMPILER_VERSION : ${CMAKE_CXX_COMPILER_VERSION}")
ENDMACRO()


# Macro to display cmake path info
MACRO(DISP_PATH_INFO)
  MSG_HDR("Path Info")
  MSG_STR("CMAKE_SOURCE_DIR         : ${CMAKE_SOURCE_DIR}")
  MSG_STR("CMAKE_BINARY_DIR         : ${CMAKE_BINARY_DIR}")
  MSG_STR("CMAKE_MODULE_PATH        : ${CMAKE_MODULE_PATH}")
  MSG_STR("LIBRARY_OUTPUT_PATH      : ${LIBRARY_OUTPUT_PATH}")
  MSG_STR("EXECUTABLE_OUTPUT_PATH   : ${EXECUTABLE_OUTPUT_PATH}")
  MSG_STR("CMAKE_PREFIX_PATH        : ${CMAKE_PREFIX_PATH}")
ENDMACRO()


# Macro to display build info
MACRO(DISP_BLD_INFO)
  MSG_HDR("Build Info")
  MSG_STR("CMAKE_BUILD_TYPE         : ${CMAKE_BUILD_TYPE}")
  MSG_STR("CMAKE_CXX_FLAGS          : ${CMAKE_CXX_FLAGS}")
  MSG_STR("CMAKE_INSTALL_PREFIX     : ${CMAKE_INSTALL_PREFIX}")
  MSG_STR("CMAKE_INSTALL_RPATH      : ${CMAKE_INSTALL_RPATH}")
ENDMACRO()


# Macro to display external lib status
MACRO(DISP_BLD_INFO)
  MSG_HDR("External Library Info")
  MSG_STR("ZMQ                      : ${_ZMQ_LIBRARY_DIR}")
  MSG_STR("CPPZMQ                   : ")
ENDMACRO()


# Run the display macros
DISP_SYS_INFO()
DISP_PROJ_INFO()
DISP_CXX_INFO()
DISP_PATH_INFO()
DISP_BLD_INFO()

