# Use root/example as user/password credentials
version: "3.1"

services:
  database:
    image: mongo
    container_name: "kitchen_monitor"
    command: --serviceExecutor adaptive
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=kitchen
      - MONGO_INITDB_ROOT_USERNAME=liam
      - MONGO_INITDB_ROOT_PASSWORD=raspberry

    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
      - ./init.sh:/docker-entrypoint-initdb.d/init-mongo.js:ro
